//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportesSacoplast.Model.ListoSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Items()
        {
            this.Items1 = new HashSet<Items>();
        }
    
        public int ItemID { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public string Caracteristicas { get; set; }
        public int LineaId { get; set; }
        public bool GrabaIVA { get; set; }
        public Nullable<decimal> Kilos { get; set; }
        public decimal Embal1 { get; set; }
        public string Reemplazos { get; set; }
        public Nullable<decimal> StockActual { get; set; }
        public decimal StockMinimo { get; set; }
        public Nullable<decimal> StockNoVenta { get; set; }
        public Nullable<decimal> StockEnTransito { get; set; }
        public Nullable<decimal> StockReservado { get; set; }
        public Nullable<decimal> StockEnTransitoPrevendido { get; set; }
        public Nullable<decimal> CostoTotal { get; set; }
        public Nullable<decimal> CostoPromedio { get; set; }
        public Nullable<decimal> UltimoCosto { get; set; }
        public Nullable<decimal> CostoFOB { get; set; }
        public string Estado { get; set; }
        public int TipoItemID { get; set; }
        public Nullable<int> UnidadId { get; set; }
        public Nullable<decimal> Embal2 { get; set; }
        public Nullable<int> MarcaId { get; set; }
        public Nullable<bool> ControlaSeries { get; set; }
        public Nullable<int> TallaID { get; set; }
        public Nullable<int> ColorID { get; set; }
        public Nullable<decimal> Precio1 { get; set; }
        public Nullable<decimal> Precio2 { get; set; }
        public Nullable<decimal> Precio3 { get; set; }
        public Nullable<decimal> Precio4 { get; set; }
        public Nullable<decimal> Precio5 { get; set; }
        public Nullable<decimal> PorcUtilidad1 { get; set; }
        public Nullable<decimal> PorcUtilidad2 { get; set; }
        public Nullable<decimal> PorcUtilidad3 { get; set; }
        public Nullable<decimal> PorcUtilidad4 { get; set; }
        public Nullable<decimal> PorcUtilidad5 { get; set; }
        public Nullable<decimal> CantMinima1 { get; set; }
        public Nullable<decimal> CantMinima2 { get; set; }
        public Nullable<decimal> CantMinima3 { get; set; }
        public Nullable<decimal> CantMinima4 { get; set; }
        public Nullable<decimal> CantMinima5 { get; set; }
        public Nullable<decimal> DolarImportacion { get; set; }
        public Nullable<int> ProveedoID { get; set; }
        public string Ubicacion { get; set; }
        public string Caduca { get; set; }
        public string Temporada { get; set; }
        public Nullable<decimal> ArancelPorc { get; set; }
        public string Genero { get; set; }
        public Nullable<decimal> CantMinimaDesc1 { get; set; }
        public Nullable<decimal> CantMinimaDesc2 { get; set; }
        public Nullable<decimal> CantMinimaDesc3 { get; set; }
        public Nullable<decimal> CantMinimaDesc4 { get; set; }
        public Nullable<decimal> CantMinimaDesc5 { get; set; }
        public Nullable<decimal> PorcentDesc1 { get; set; }
        public Nullable<decimal> PorcentDesc2 { get; set; }
        public Nullable<decimal> PorcentDesc3 { get; set; }
        public Nullable<decimal> PorcentDesc4 { get; set; }
        public Nullable<decimal> PorcentDesc5 { get; set; }
        public Nullable<decimal> ValorOriginal { get; set; }
        public Nullable<decimal> ValorResidual { get; set; }
        public Nullable<decimal> VidaUtil { get; set; }
        public Nullable<decimal> DeprecAcumulada { get; set; }
        public Nullable<decimal> DeprecAnual { get; set; }
        public Nullable<System.DateTime> FechaAdqusicion { get; set; }
        public Nullable<System.DateTime> FechaBase { get; set; }
        public Nullable<int> UnidadMedida_UnidadMedidaID { get; set; }
        public byte[] RowVersion { get; set; }
        public string Catalogo { get; set; }
        public Nullable<int> BodegaID { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public Nullable<decimal> ArancelValor { get; set; }
        public Nullable<int> SucursalID { get; set; }
        public Nullable<System.DateTime> PrimeraCompra { get; set; }
        public Nullable<System.DateTime> UltimaCompra { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string RutaImagen { get; set; }
        public string Imagen { get; set; }
        public string TipoControlInventario { get; set; }
        public Nullable<decimal> CantidadUnitariaComponentes { get; set; }
        public Nullable<int> SubLineaID { get; set; }
        public Nullable<int> BodegaIDUbicacion { get; set; }
        public Nullable<decimal> ValorActual { get; set; }
        public string IDConsolidado { get; set; }
        public Nullable<int> UnidadMedidaIDAlterna { get; set; }
        public Nullable<decimal> FactorDeConversion { get; set; }
        public Nullable<bool> EsGasto { get; set; }
        public Nullable<decimal> DepreciacionInicialAcumulada { get; set; }
        public Nullable<System.DateTime> FechaInicialDepreciacion { get; set; }
        public Nullable<int> PartidaArancelariaID { get; set; }
        public Nullable<decimal> StockPorProducir { get; set; }
        public Nullable<decimal> StockParaProducir { get; set; }
        public Nullable<decimal> StockMaximo { get; set; }
        public Nullable<int> CasilleroICEID { get; set; }
        public Nullable<decimal> FactorProrrateoTransformaciones { get; set; }
        public Nullable<bool> EstaDadoBaja { get; set; }
        public Nullable<decimal> CostoReposicion { get; set; }
        public Nullable<int> ItemIDComodin { get; set; }
    
        public virtual Lineas Lineas { get; set; }
        public virtual Lineas Lineas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Items> Items1 { get; set; }
        public virtual Items Items2 { get; set; }
    }
}
