//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportesSacoplast.Model.ListoSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lineas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lineas()
        {
            this.Items = new HashSet<Items>();
            this.Items1 = new HashSet<Items>();
            this.Lineas1 = new HashSet<Lineas>();
        }
    
        public int LineaID { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> CuentaIDVenta { get; set; }
        public Nullable<int> CuentaIDVentaNoSRI { get; set; }
        public Nullable<int> CuentaIDCosto { get; set; }
        public Nullable<int> CuentaIDDescuento { get; set; }
        public Nullable<int> CuentaIDInventario { get; set; }
        public Nullable<int> CuentaIDGastos { get; set; }
        public Nullable<int> LineaIDPadre { get; set; }
        public byte[] RowVersion { get; set; }
        public Nullable<int> CentroCostoID { get; set; }
        public Nullable<int> SubCentroCostoID { get; set; }
        public Nullable<int> CuentaIDDescuentoNOSRI { get; set; }
        public Nullable<int> CuentaIDActivoFijo { get; set; }
        public Nullable<int> CuentaIDDepreciacionAcumulada { get; set; }
        public Nullable<int> CuentaIDGastoDepreciacion { get; set; }
        public Nullable<int> CuentaIDDeterioroAcumulado { get; set; }
        public Nullable<int> CuentaIDGastoDeterioro { get; set; }
        public Nullable<int> CuentaIDBajas { get; set; }
        public Nullable<int> TipoItemID { get; set; }
        public Nullable<int> CuentaIDRevalorizacion { get; set; }
        public string IDConsolidado { get; set; }
        public Nullable<int> VidaUtilAños { get; set; }
        public Nullable<int> CuentaIDCostoActivoFijo { get; set; }
        public Nullable<decimal> PorcValorResidual { get; set; }
        public Nullable<int> CuentaIDAplicacionCostos { get; set; }
        public Nullable<int> CuentaIDVentaAF { get; set; }
        public Nullable<int> CuentaIDVentaNoSRIAF { get; set; }
        public Nullable<int> CuentaIDAplicacionCostosOT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Items> Items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Items> Items1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lineas> Lineas1 { get; set; }
        public virtual Lineas Lineas2 { get; set; }
    }
}
